using System;
using SqlSugar;
using La.Infra.Attribute;
using La.Model;
using La.Model.Dto;
using La.Model.Models;
using La.Model.System;
using La.Repository;
using La.Service.Material.IMaterialService;
using System.Linq;

namespace La.Service.Material
{
    /// <summary>
    /// 工厂物料数据Service业务层处理
    ///
    /// @author Laplace.Net:Davis.Cheng
    /// @date 2023-03-14
    /// </summary>
    [AppService(ServiceType = typeof(IMmMarcService), ServiceLifetime = LifeTime.Transient)]
    public class MmMarcService : BaseService<MmMarc>, IMmMarcService
    {
        #region 业务逻辑代码

        /// <summary>
        /// 查询工厂物料数据列表
        /// </summary>
        /// <param name="parm"></param>
        /// <returns></returns>
        public PagedInfo<MmMarcDto> GetList(MmMarcQueryDto parm)
        {
            //开始拼装查询条件
            var predicate = Expressionable.Create<MmMarc>();

            //搜索条件查询语法参考Sqlsugar
            var response = Queryable()
                //.OrderBy("MarcMATNR asc")
                .Where(predicate.ToExpression())
                .ToPage<MmMarc, MmMarcDto>(parm);

            return response;
        }


        /// <summary>
        /// 校验输入项目是否唯一
        /// </summary>
        /// <param name="entryString"></param>
        /// <returns></returns>
        public string CheckEntryStringUnique(string entryString)
        {
            int count = Count(it => it.MarcID.ToString() == entryString);
            if (count > 0)
            {
                return UserConstants.NOT_UNIQUE;
            }
            return UserConstants.UNIQUE;
        }

        /// <summary>
        /// 添加工厂物料数据
        /// </summary>
        /// <param name="parm"></param>
        /// <returns></returns>
        public int AddMmMarc(MmMarc parm)
        {
            var response = Insert(parm, it => new
            {
                it.MarcABCIN,
                it.MarcABFAC,
                it.MarcAHDIS,
                it.MarcALTSL,
                it.MarcAPLAL,
                it.MarcAPOKZ,
                it.MarcATPKZ,
                it.MarcAUFTL,
                it.MarcAUSDT,
                it.MarcAUSME,
                it.MarcAUSSS,
                it.MarcAUTRU,
                it.MarcAWSLS,
                it.MarcBASMG,
                it.MarcBEARZ,
                it.MarcBESKZ,
                it.MarcBSTFE,
                it.MarcBSTMA,
                it.MarcBSTMI,
                it.MarcBSTRF,
                it.MarcBWESB,
                it.MarcBWSCL,
                it.MarcBWTTY,
                it.MarcCASNR,
                it.MarcCCFIX,
                it.MarcCOMPL,
                it.MarcconsProcg,
                it.MarcCONVT,
                it.MarcCOPAM,
                it.MarcCUOBJ,
                it.MarcCUOBV,
                it.MarcDIBER,
                it.MarcDISGR,
                it.MarcDISLS,
                it.MarcDISMM,
                it.MarcDISPO,
                it.MarcDISPR,
                it.MarcDPLFS,
                it.MarcDPLHO,
                it.MarcDPLPU,
                it.MarcDZEIT,
                it.MarcEISBE,
                it.MarcEISLO,
                it.MarcEKGRP,
                it.MarcEPRIO,
                it.MarcEXPME,
                it.MarcFABKZ,
                it.MarcFEVOR,
                it.MarcFFREI,
                it.MarcFHORI,
                it.MarcFIXLS,
                it.MarcFPRFM,
                it.MarcFRTME,
                it.MarcfshMgArunReq,
                it.MarcfshSeaim,
                it.MarcFVIDK,
                it.MarcFXHOR,
                it.MarcFXPRU,
                it.MarcgiPrTime,
                it.MarcGLGMG,
                it.MarcGPMKZ,
                it.MarcGPNUM,
                it.MarcHERBL,
                it.MarcHERKL,
                it.MarcHERKR,
                it.MarcINDUS,
                it.MarcINSMK,
                it.MarcITARK,
                it.MarciuidRelevant,
                it.MarciuidType,
                it.MarcKAUSF,
                it.MarcKAUTB,
                it.MarcKORDB,
                it.MarcKZAGL,
                it.MarcKZAUS,
                it.MarcKZBED,
                it.MarcKZDIE,
                it.MarcKZDKZ,
                it.MarcKZECH,
                it.MarcKZKFK,
                it.MarcKZKRI,
                it.MarcKZKUP,
                it.MarcKZPPV,
                it.MarcKZPRO,
                it.MarcKZPSP,
                it.MarcLADGR,
                it.MarcLAGPR,
                it.MarcLFGJA,
                it.MarcLFMON,
                it.MarcLFRHY,
                it.MarcLGFSB,
                it.MarcLGPRO,
                it.MarcLGRAD,
                it.MarcLIZYK,
                it.MarcLOGGR,
                it.MarcLOSFX,
                it.MarcLOSGR,
                it.MarcLTINC,
                it.MarcLVORM,
                it.MarcLZEIH,
                it.MarcMAABC,
                it.MarcMABST,
                it.MarcMANDT,
                it.MarcMATGR,
                it.MarcMATNR,
                it.MarcmaxTroc,
                it.MarcMAXLS,
                it.MarcMAXLZ,
                it.MarcMCRUE,
                it.MarcMDACH,
                it.MarcMEGRU,
                it.MarcMFRGR,
                it.MarcminTroc,
                it.MarcMINBE,
                it.MarcMINLS,
                it.MarcMISKZ,
                it.MarcMMSTA,
                it.MarcMMSTD,
                it.MarcMOGRU,
                it.MarcMOWNR,
                it.MarcMPDAU,
                it.MarcMRPPP,
                it.MarcMTVER,
                it.MarcMTVFP,
                it.MarcmultipleEkgrp,
                it.MarcNCOST,
                it.MarcNFMAT,
                it.MarcNKMPR,
                it.MarcOBJID,
                it.MarcOCMPF,
                it.MarcOTYPE,
                it.MarcPERIV,
                it.MarcPERKZ,
                it.MarcPFREI,
                it.MarcPLIFZ,
                it.MarcPLNNR,
                it.MarcPLNTY,
                it.MarcPLVAR,
                it.MarcPRCTR,
                it.MarcPREFE,
                it.MarcPRENC,
                it.MarcPREND,
                it.MarcPRENE,
                it.MarcPRENG,
                it.MarcPRENO,
                it.MarcPRFRQ,
                it.MarcPSTAT,
                it.MarcQMATA,
                it.MarcQMATV,
                it.MarcQSSYS,
                it.MarcQUAZT,
                it.MarcQZGTP,
                it.MarcRDPRF,
                it.MarcrefSchema,
                it.MarcRESVP,
                it.MarcRGEKZ,
                it.MarcrotationDate,
                it.MarcRUEZT,
                it.MarcRWPRO,
                it.MarcSAUFT,
                it.MarcSBDKZ,
                it.MarcSCHGT,
                it.MarcSERNP,
                it.MarcSERVG,
                it.MarcSFCPF,
                it.MarcSFEPR,
                it.MarcsgtChint,
                it.MarcsgtCovs,
                it.MarcsgtMrpsi,
                it.MarcsgtPrcm,
                it.MarcsgtScope,
                it.MarcsgtStatc,
                it.MarcsgtStkPrt,
                it.MarcSHFLG,
                it.MarcSHPRO,
                it.MarcSHZET,
                it.MarcSOBSK,
                it.MarcSOBSL,
                it.MarcSPROZ,
                it.MarcSSQSS,
                it.MarcSTAWN,
                it.MarcSTDPD,
                it.MarcSTEUC,
                it.MarcSTLAL,
                it.MarcSTLAN,
                it.MarcSTRGR,
                it.MarcTAKZT,
                it.MarctargetStock,
                it.MarcTRAME,
                it.MarcTRANZ,
                it.MarcUCHKZ,
                it.MarcUCMAT,
                it.MarcUEETK,
                it.MarcUEETO,
                it.MarcuidIea,
                it.MarcUMLMC,
                it.MarcUMRSL,
                it.MarcUNETO,
                it.MarcUOMGR,
                it.MarcUSEQU,
                it.MarcVBAMG,
                it.MarcVBEAZ,
                it.MarcVERKZ,
                it.MarcVINT1,
                it.MarcVINT2,
                it.MarcVKGLG,
                it.MarcVKTRW,
                it.MarcVKUMC,
                it.MarcVRBDT,
                it.MarcVRBFK,
                it.MarcVRBMT,
                it.MarcVRBWK,
                it.MarcVRMOD,
                it.MarcVRVEZ,
                it.MarcVSPVB,
                it.MarcVZUSL,
                it.MarcWEBAZ,
                it.MarcWERKS,
                it.MarcWSTGH,
                it.MarcWZEIT,
                it.MarcXCHAR,
                it.MarcXCHPF,
                it.MarcXMCNG,
                it.UDF01,
                it.UDF02,
                it.UDF03,
                it.UDF04,
                it.UDF05,
                it.UDF06,
                it.UDF51,
                it.UDF52,
                it.UDF53,
                it.UDF54,
                it.UDF55,
                it.UDF56,
                it.IsDeleted,
                it.Remark,
                it.CreateBy,
                it.CreateTime,
                it.UpdateBy,
                it.UpdateTime,
            });
            return response;
        }

        /// <summary>
        /// 修改工厂物料数据
        /// </summary>
        /// <param name="parm"></param>
        /// <returns></returns>
        public int UpdateMmMarc(MmMarc parm)
        {
            var response = Update(w => w.MarcID == parm.MarcID, it => new MmMarc()
            {
                MarcABCIN = parm.MarcABCIN,
                MarcABFAC = parm.MarcABFAC,
                MarcAHDIS = parm.MarcAHDIS,
                MarcALTSL = parm.MarcALTSL,
                MarcAPLAL = parm.MarcAPLAL,
                MarcAPOKZ = parm.MarcAPOKZ,
                MarcATPKZ = parm.MarcATPKZ,
                MarcAUFTL = parm.MarcAUFTL,
                MarcAUSDT = parm.MarcAUSDT,
                MarcAUSME = parm.MarcAUSME,
                MarcAUSSS = parm.MarcAUSSS,
                MarcAUTRU = parm.MarcAUTRU,
                MarcAWSLS = parm.MarcAWSLS,
                MarcBASMG = parm.MarcBASMG,
                MarcBEARZ = parm.MarcBEARZ,
                MarcBESKZ = parm.MarcBESKZ,
                MarcBSTFE = parm.MarcBSTFE,
                MarcBSTMA = parm.MarcBSTMA,
                MarcBSTMI = parm.MarcBSTMI,
                MarcBSTRF = parm.MarcBSTRF,
                MarcBWESB = parm.MarcBWESB,
                MarcBWSCL = parm.MarcBWSCL,
                MarcBWTTY = parm.MarcBWTTY,
                MarcCASNR = parm.MarcCASNR,
                MarcCCFIX = parm.MarcCCFIX,
                MarcCOMPL = parm.MarcCOMPL,
                MarcconsProcg = parm.MarcconsProcg,
                MarcCONVT = parm.MarcCONVT,
                MarcCOPAM = parm.MarcCOPAM,
                MarcCUOBJ = parm.MarcCUOBJ,
                MarcCUOBV = parm.MarcCUOBV,
                MarcDIBER = parm.MarcDIBER,
                MarcDISGR = parm.MarcDISGR,
                MarcDISLS = parm.MarcDISLS,
                MarcDISMM = parm.MarcDISMM,
                MarcDISPO = parm.MarcDISPO,
                MarcDISPR = parm.MarcDISPR,
                MarcDPLFS = parm.MarcDPLFS,
                MarcDPLHO = parm.MarcDPLHO,
                MarcDPLPU = parm.MarcDPLPU,
                MarcDZEIT = parm.MarcDZEIT,
                MarcEISBE = parm.MarcEISBE,
                MarcEISLO = parm.MarcEISLO,
                MarcEKGRP = parm.MarcEKGRP,
                MarcEPRIO = parm.MarcEPRIO,
                MarcEXPME = parm.MarcEXPME,
                MarcFABKZ = parm.MarcFABKZ,
                MarcFEVOR = parm.MarcFEVOR,
                MarcFFREI = parm.MarcFFREI,
                MarcFHORI = parm.MarcFHORI,
                MarcFIXLS = parm.MarcFIXLS,
                MarcFPRFM = parm.MarcFPRFM,
                MarcFRTME = parm.MarcFRTME,
                MarcfshMgArunReq = parm.MarcfshMgArunReq,
                MarcfshSeaim = parm.MarcfshSeaim,
                MarcFVIDK = parm.MarcFVIDK,
                MarcFXHOR = parm.MarcFXHOR,
                MarcFXPRU = parm.MarcFXPRU,
                MarcgiPrTime = parm.MarcgiPrTime,
                MarcGLGMG = parm.MarcGLGMG,
                MarcGPMKZ = parm.MarcGPMKZ,
                MarcGPNUM = parm.MarcGPNUM,
                MarcHERBL = parm.MarcHERBL,
                MarcHERKL = parm.MarcHERKL,
                MarcHERKR = parm.MarcHERKR,
                MarcINDUS = parm.MarcINDUS,
                MarcINSMK = parm.MarcINSMK,
                MarcITARK = parm.MarcITARK,
                MarciuidRelevant = parm.MarciuidRelevant,
                MarciuidType = parm.MarciuidType,
                MarcKAUSF = parm.MarcKAUSF,
                MarcKAUTB = parm.MarcKAUTB,
                MarcKORDB = parm.MarcKORDB,
                MarcKZAGL = parm.MarcKZAGL,
                MarcKZAUS = parm.MarcKZAUS,
                MarcKZBED = parm.MarcKZBED,
                MarcKZDIE = parm.MarcKZDIE,
                MarcKZDKZ = parm.MarcKZDKZ,
                MarcKZECH = parm.MarcKZECH,
                MarcKZKFK = parm.MarcKZKFK,
                MarcKZKRI = parm.MarcKZKRI,
                MarcKZKUP = parm.MarcKZKUP,
                MarcKZPPV = parm.MarcKZPPV,
                MarcKZPRO = parm.MarcKZPRO,
                MarcKZPSP = parm.MarcKZPSP,
                MarcLADGR = parm.MarcLADGR,
                MarcLAGPR = parm.MarcLAGPR,
                MarcLFGJA = parm.MarcLFGJA,
                MarcLFMON = parm.MarcLFMON,
                MarcLFRHY = parm.MarcLFRHY,
                MarcLGFSB = parm.MarcLGFSB,
                MarcLGPRO = parm.MarcLGPRO,
                MarcLGRAD = parm.MarcLGRAD,
                MarcLIZYK = parm.MarcLIZYK,
                MarcLOGGR = parm.MarcLOGGR,
                MarcLOSFX = parm.MarcLOSFX,
                MarcLOSGR = parm.MarcLOSGR,
                MarcLTINC = parm.MarcLTINC,
                MarcLVORM = parm.MarcLVORM,
                MarcLZEIH = parm.MarcLZEIH,
                MarcMAABC = parm.MarcMAABC,
                MarcMABST = parm.MarcMABST,
                MarcMANDT = parm.MarcMANDT,
                MarcMATGR = parm.MarcMATGR,
                MarcMATNR = parm.MarcMATNR,
                MarcmaxTroc = parm.MarcmaxTroc,
                MarcMAXLS = parm.MarcMAXLS,
                MarcMAXLZ = parm.MarcMAXLZ,
                MarcMCRUE = parm.MarcMCRUE,
                MarcMDACH = parm.MarcMDACH,
                MarcMEGRU = parm.MarcMEGRU,
                MarcMFRGR = parm.MarcMFRGR,
                MarcminTroc = parm.MarcminTroc,
                MarcMINBE = parm.MarcMINBE,
                MarcMINLS = parm.MarcMINLS,
                MarcMISKZ = parm.MarcMISKZ,
                MarcMMSTA = parm.MarcMMSTA,
                MarcMMSTD = parm.MarcMMSTD,
                MarcMOGRU = parm.MarcMOGRU,
                MarcMOWNR = parm.MarcMOWNR,
                MarcMPDAU = parm.MarcMPDAU,
                MarcMRPPP = parm.MarcMRPPP,
                MarcMTVER = parm.MarcMTVER,
                MarcMTVFP = parm.MarcMTVFP,
                MarcmultipleEkgrp = parm.MarcmultipleEkgrp,
                MarcNCOST = parm.MarcNCOST,
                MarcNFMAT = parm.MarcNFMAT,
                MarcNKMPR = parm.MarcNKMPR,
                MarcOBJID = parm.MarcOBJID,
                MarcOCMPF = parm.MarcOCMPF,
                MarcOTYPE = parm.MarcOTYPE,
                MarcPERIV = parm.MarcPERIV,
                MarcPERKZ = parm.MarcPERKZ,
                MarcPFREI = parm.MarcPFREI,
                MarcPLIFZ = parm.MarcPLIFZ,
                MarcPLNNR = parm.MarcPLNNR,
                MarcPLNTY = parm.MarcPLNTY,
                MarcPLVAR = parm.MarcPLVAR,
                MarcPRCTR = parm.MarcPRCTR,
                MarcPREFE = parm.MarcPREFE,
                MarcPRENC = parm.MarcPRENC,
                MarcPREND = parm.MarcPREND,
                MarcPRENE = parm.MarcPRENE,
                MarcPRENG = parm.MarcPRENG,
                MarcPRENO = parm.MarcPRENO,
                MarcPRFRQ = parm.MarcPRFRQ,
                MarcPSTAT = parm.MarcPSTAT,
                MarcQMATA = parm.MarcQMATA,
                MarcQMATV = parm.MarcQMATV,
                MarcQSSYS = parm.MarcQSSYS,
                MarcQUAZT = parm.MarcQUAZT,
                MarcQZGTP = parm.MarcQZGTP,
                MarcRDPRF = parm.MarcRDPRF,
                MarcrefSchema = parm.MarcrefSchema,
                MarcRESVP = parm.MarcRESVP,
                MarcRGEKZ = parm.MarcRGEKZ,
                MarcrotationDate = parm.MarcrotationDate,
                MarcRUEZT = parm.MarcRUEZT,
                MarcRWPRO = parm.MarcRWPRO,
                MarcSAUFT = parm.MarcSAUFT,
                MarcSBDKZ = parm.MarcSBDKZ,
                MarcSCHGT = parm.MarcSCHGT,
                MarcSERNP = parm.MarcSERNP,
                MarcSERVG = parm.MarcSERVG,
                MarcSFCPF = parm.MarcSFCPF,
                MarcSFEPR = parm.MarcSFEPR,
                MarcsgtChint = parm.MarcsgtChint,
                MarcsgtCovs = parm.MarcsgtCovs,
                MarcsgtMrpsi = parm.MarcsgtMrpsi,
                MarcsgtPrcm = parm.MarcsgtPrcm,
                MarcsgtScope = parm.MarcsgtScope,
                MarcsgtStatc = parm.MarcsgtStatc,
                MarcsgtStkPrt = parm.MarcsgtStkPrt,
                MarcSHFLG = parm.MarcSHFLG,
                MarcSHPRO = parm.MarcSHPRO,
                MarcSHZET = parm.MarcSHZET,
                MarcSOBSK = parm.MarcSOBSK,
                MarcSOBSL = parm.MarcSOBSL,
                MarcSPROZ = parm.MarcSPROZ,
                MarcSSQSS = parm.MarcSSQSS,
                MarcSTAWN = parm.MarcSTAWN,
                MarcSTDPD = parm.MarcSTDPD,
                MarcSTEUC = parm.MarcSTEUC,
                MarcSTLAL = parm.MarcSTLAL,
                MarcSTLAN = parm.MarcSTLAN,
                MarcSTRGR = parm.MarcSTRGR,
                MarcTAKZT = parm.MarcTAKZT,
                MarctargetStock = parm.MarctargetStock,
                MarcTRAME = parm.MarcTRAME,
                MarcTRANZ = parm.MarcTRANZ,
                MarcUCHKZ = parm.MarcUCHKZ,
                MarcUCMAT = parm.MarcUCMAT,
                MarcUEETK = parm.MarcUEETK,
                MarcUEETO = parm.MarcUEETO,
                MarcuidIea = parm.MarcuidIea,
                MarcUMLMC = parm.MarcUMLMC,
                MarcUMRSL = parm.MarcUMRSL,
                MarcUNETO = parm.MarcUNETO,
                MarcUOMGR = parm.MarcUOMGR,
                MarcUSEQU = parm.MarcUSEQU,
                MarcVBAMG = parm.MarcVBAMG,
                MarcVBEAZ = parm.MarcVBEAZ,
                MarcVERKZ = parm.MarcVERKZ,
                MarcVINT1 = parm.MarcVINT1,
                MarcVINT2 = parm.MarcVINT2,
                MarcVKGLG = parm.MarcVKGLG,
                MarcVKTRW = parm.MarcVKTRW,
                MarcVKUMC = parm.MarcVKUMC,
                MarcVRBDT = parm.MarcVRBDT,
                MarcVRBFK = parm.MarcVRBFK,
                MarcVRBMT = parm.MarcVRBMT,
                MarcVRBWK = parm.MarcVRBWK,
                MarcVRMOD = parm.MarcVRMOD,
                MarcVRVEZ = parm.MarcVRVEZ,
                MarcVSPVB = parm.MarcVSPVB,
                MarcVZUSL = parm.MarcVZUSL,
                MarcWEBAZ = parm.MarcWEBAZ,
                MarcWERKS = parm.MarcWERKS,
                MarcWSTGH = parm.MarcWSTGH,
                MarcWZEIT = parm.MarcWZEIT,
                MarcXCHAR = parm.MarcXCHAR,
                MarcXCHPF = parm.MarcXCHPF,
                MarcXMCNG = parm.MarcXMCNG,
                UDF01 = parm.UDF01,
                UDF02 = parm.UDF02,
                UDF03 = parm.UDF03,
                UDF04 = parm.UDF04,
                UDF05 = parm.UDF05,
                UDF06 = parm.UDF06,
                UDF51 = parm.UDF51,
                UDF52 = parm.UDF52,
                UDF53 = parm.UDF53,
                UDF54 = parm.UDF54,
                UDF55 = parm.UDF55,
                UDF56 = parm.UDF56,
                Remark = parm.Remark,
            });
            return response;
        }

        /// <summary>
        /// 清空工厂物料数据
        /// </summary>
        /// <returns></returns>
        public void TruncateMmMarc()
        {
            Truncate();
        }
        #endregion
    }
}