using System;
using SqlSugar;
using La.Infra.Attribute;
using La.Model;
using La.Model.Dto;
using La.Model.Models;
using La.Model.System;
using La.Repository;
using La.Service.Material.IMaterialService;
using System.Linq;

namespace La.Service.Material
{
    /// <summary>
    /// 常规物料数据Service业务层处理
    ///
    /// @author Laplace.Net:Davis.Cheng
    /// @date 2023-03-14
    /// </summary>
    [AppService(ServiceType = typeof(IMmMaraService), ServiceLifetime = LifeTime.Transient)]
    public class MmMaraService : BaseService<MmMara>, IMmMaraService
    {
        #region 业务逻辑代码

        /// <summary>
        /// 查询常规物料数据列表
        /// </summary>
        /// <param name="parm"></param>
        /// <returns></returns>
        public PagedInfo<MmMaraDto> GetList(MmMaraQueryDto parm)
        {
            //开始拼装查询条件
            var predicate = Expressionable.Create<MmMara>();

            //搜索条件查询语法参考Sqlsugar
            var response = Queryable()
                //.OrderBy("MaraMATNR asc")
                .Where(predicate.ToExpression())
                .ToPage<MmMara, MmMaraDto>(parm);

            return response;
        }


        /// <summary>
        /// 校验输入项目是否唯一
        /// </summary>
        /// <param name="entryString"></param>
        /// <returns></returns>
        public string CheckEntryStringUnique(string entryString)
        {
            int count = Count(it => it.MaraID.ToString() == entryString);
            if (count > 0)
            {
                return UserConstants.NOT_UNIQUE;
            }
            return UserConstants.UNIQUE;
        }

        /// <summary>
        /// 添加常规物料数据
        /// </summary>
        /// <param name="parm"></param>
        /// <returns></returns>
        public int AddMmMara(MmMara parm)
        {
            var response = Insert(parm, it => new
            {
                it.MaraADPROF,
                it.MaraAEKLK,
                it.MaraAENAM,
                it.MaraAESZN,
                it.MaraallowPmatIgno,
                it.MaraanimalOrigin,
                it.MaraANP,
                it.MaraATTYP,
                it.MaraBBTYP,
                it.MaraBEGRU,
                it.MaraBEHVO,
                it.MaraBFLME,
                it.MaraBISMT,
                it.MaraBLANZ,
                it.MaraBLATT,
                it.MaraBMATN,
                it.MarabrandId,
                it.MaraBREIT,
                it.MaraBRGEW,
                it.MaraBSTAT,
                it.MaraBSTME,
                it.MaraBWSCL,
                it.MaraBWVOR,
                it.MaraCADKZ,
                it.MaracareCode,
                it.MaraCMETH,
                it.MaraCMREL,
                it.MaraCOLOR,
                it.MaracolorAtinn,
                it.MaraCOMMODITY,
                it.MaraCOMPL,
                it.MaraCUOBF,
                it.MaraCWQPROC,
                it.MaraCWQREL,
                it.MaraCWQTOLGR,
                it.MaraDATAB,
                it.MaradgPackStatus,
                it.MaraDISST,
                it.MaraEAN11,
                it.MaraEANNR,
                it.MaraEKWSL,
                it.MaraENTAR,
                it.MaraERGEI,
                it.MaraERGEW,
                it.MaraERNAM,
                it.MaraERSDA,
                it.MaraERVOE,
                it.MaraERVOL,
                it.MaraETIAG,
                it.MaraETIAR,
                it.MaraETIFO,
                it.MaraEXTWG,
                it.MaraFASHGRD,
                it.MaraFERTH,
                it.MarafiberCode1,
                it.MarafiberCode2,
                it.MarafiberCode3,
                it.MarafiberCode4,
                it.MarafiberCode5,
                it.MarafiberPart1,
                it.MarafiberPart2,
                it.MarafiberPart3,
                it.MarafiberPart4,
                it.MarafiberPart5,
                it.MaraFORMT,
                it.MarafreeChar,
                it.MarafshMgAt1,
                it.MarafshMgAt2,
                it.MarafshMgAt3,
                it.MarafshScMid,
                it.MarafshSeaim,
                it.MarafshSealv,
                it.MaraFUELG,
                it.MaragdsRelevant,
                it.MaraGENNR,
                it.MaraGEWEI,
                it.MaraGEWTO,
                it.MaraGROES,
                it.MaragtinVariant,
                it.MaraHAZMAT,
                it.MaraHERKL,
                it.MaraHNDLCODE,
                it.MaraHOEHE,
                it.MaraHUTYP,
                it.MarahutypDflt,
                it.MaraIHIVI,
                it.MaraILOOS,
                it.MaraIMATN,
                it.MaraINHAL,
                it.MaraINHBR,
                it.MaraINHME,
                it.MaraIPMIPPRODUCT,
                it.MaraIPRKZ,
                it.MaraKOSCH,
                it.MaraKUNNR,
                it.MaraKZEFF,
                it.MaraKZGVH,
                it.MaraKZKFG,
                it.MaraKZKUP,
                it.MaraKZNFM,
                it.MaraKZREV,
                it.MaraKZUMW,
                it.MaraKZWSM,
                it.MaraLABOR,
                it.MaraLAEDA,
                it.MaraLAENG,
                it.MaraLIQDT,
                it.MaraloglevReto,
                it.MaraLOGUNIT,
                it.MaraLVORM,
                it.MaraMAGRV,
                it.MaraMANDT,
                it.MaraMATFI,
                it.MaraMATKL,
                it.MaraMATNR,
                it.MaraMAXB,
                it.MaraMAXC,
                it.MaramaxcTol,
                it.MaramaxdimUom,
                it.MaraMAXH,
                it.MaraMAXL,
                it.MaraMBRSH,
                it.MaraMCOND,
                it.MaraMEABM,
                it.MaraMEDIUM,
                it.MaraMEINS,
                it.MaraMFRGR,
                it.MaraMFRNR,
                it.MaraMFRPN,
                it.MaraMHDHB,
                it.MaraMHDLP,
                it.MaraMHDRZ,
                it.MaraMLGUT,
                it.MaraMPROF,
                it.MaraMSTAE,
                it.MaraMSTAV,
                it.MaraMSTDE,
                it.MaraMSTDV,
                it.MaraMTART,
                it.MaramtposMara,
                it.MaraNORMT,
                it.MaraNRFHG,
                it.MaraNSNID,
                it.MaraNTGEW,
                it.MaraNUMTP,
                it.MaraPACKCODE,
                it.MaraPICNUM,
                it.MaraPILFERABLE,
                it.MaraPLGTP,
                it.MaraPMATA,
                it.MaraPRDHA,
                it.MaraPROFL,
                it.MaraPRZUS,
                it.MarapsSmartform,
                it.MaraPSTAT,
                it.MaraQGRP,
                it.MaraQMPUR,
                it.MaraQQTIME,
                it.MaraQQTIMEUOM,
                it.MaraRAUBE,
                it.MaraRBNRM,
                it.MaraRDMHD,
                it.MaraRETDELC,
                it.MaraRMATP,
                it.MaraSAISJ,
                it.MaraSAISO,
                it.MaraSAITY,
                it.MaraSATNR,
                it.MaraSERIAL,
                it.MaraSERLV,
                it.MarasgtCovsa,
                it.MarasgtCsgr,
                it.MarasgtRel,
                it.MarasgtScope,
                it.MarasgtStat,
                it.MaraSIZE1,
                it.Marasize1Atinn,
                it.MaraSIZE2,
                it.Marasize2Atinn,
                it.MarasledBbd,
                it.MaraSPART,
                it.MaraSPROF,
                it.MaraSTFAK,
                it.MaraSTOFF,
                it.MaraTAKLV,
                it.MaratareVar,
                it.MaraTEMPB,
                it.MaratextileCompInd,
                it.MaraTRAGR,
                it.MaraVABME,
                it.MaraVHART,
                it.MaraVOLEH,
                it.MaraVOLTO,
                it.MaraVOLUM,
                it.MaraVPREH,
                it.MaraVPSTA,
                it.MaraWEORA,
                it.MaraWESCH,
                it.MaraWHMATGR,
                it.MaraWHSTC,
                it.MaraWRKST,
                it.MaraXCHPF,
                it.MaraXGCHP,
                it.MaraZEIAR,
                it.MaraZEIFO,
                it.MaraZEINR,
                it.MaraZEIVR,
                it.UDF01,
                it.UDF02,
                it.UDF03,
                it.UDF04,
                it.UDF05,
                it.UDF06,
                it.UDF51,
                it.UDF52,
                it.UDF53,
                it.UDF54,
                it.UDF55,
                it.UDF56,
                it.IsDeleted,
                it.Remark,
                it.CreateBy,
                it.CreateTime,
                it.UpdateBy,
                it.UpdateTime,
            });
            return response;
        }

        /// <summary>
        /// 修改常规物料数据
        /// </summary>
        /// <param name="parm"></param>
        /// <returns></returns>
        public int UpdateMmMara(MmMara parm)
        {
            var response = Update(w => w.MaraID == parm.MaraID, it => new MmMara()
            {
                MaraADPROF = parm.MaraADPROF,
                MaraAEKLK = parm.MaraAEKLK,
                MaraAENAM = parm.MaraAENAM,
                MaraAESZN = parm.MaraAESZN,
                MaraallowPmatIgno = parm.MaraallowPmatIgno,
                MaraanimalOrigin = parm.MaraanimalOrigin,
                MaraANP = parm.MaraANP,
                MaraATTYP = parm.MaraATTYP,
                MaraBBTYP = parm.MaraBBTYP,
                MaraBEGRU = parm.MaraBEGRU,
                MaraBEHVO = parm.MaraBEHVO,
                MaraBFLME = parm.MaraBFLME,
                MaraBISMT = parm.MaraBISMT,
                MaraBLANZ = parm.MaraBLANZ,
                MaraBLATT = parm.MaraBLATT,
                MaraBMATN = parm.MaraBMATN,
                MarabrandId = parm.MarabrandId,
                MaraBREIT = parm.MaraBREIT,
                MaraBRGEW = parm.MaraBRGEW,
                MaraBSTAT = parm.MaraBSTAT,
                MaraBSTME = parm.MaraBSTME,
                MaraBWSCL = parm.MaraBWSCL,
                MaraBWVOR = parm.MaraBWVOR,
                MaraCADKZ = parm.MaraCADKZ,
                MaracareCode = parm.MaracareCode,
                MaraCMETH = parm.MaraCMETH,
                MaraCMREL = parm.MaraCMREL,
                MaraCOLOR = parm.MaraCOLOR,
                MaracolorAtinn = parm.MaracolorAtinn,
                MaraCOMMODITY = parm.MaraCOMMODITY,
                MaraCOMPL = parm.MaraCOMPL,
                MaraCUOBF = parm.MaraCUOBF,
                MaraCWQPROC = parm.MaraCWQPROC,
                MaraCWQREL = parm.MaraCWQREL,
                MaraCWQTOLGR = parm.MaraCWQTOLGR,
                MaraDATAB = parm.MaraDATAB,
                MaradgPackStatus = parm.MaradgPackStatus,
                MaraDISST = parm.MaraDISST,
                MaraEAN11 = parm.MaraEAN11,
                MaraEANNR = parm.MaraEANNR,
                MaraEKWSL = parm.MaraEKWSL,
                MaraENTAR = parm.MaraENTAR,
                MaraERGEI = parm.MaraERGEI,
                MaraERGEW = parm.MaraERGEW,
                MaraERNAM = parm.MaraERNAM,
                MaraERSDA = parm.MaraERSDA,
                MaraERVOE = parm.MaraERVOE,
                MaraERVOL = parm.MaraERVOL,
                MaraETIAG = parm.MaraETIAG,
                MaraETIAR = parm.MaraETIAR,
                MaraETIFO = parm.MaraETIFO,
                MaraEXTWG = parm.MaraEXTWG,
                MaraFASHGRD = parm.MaraFASHGRD,
                MaraFERTH = parm.MaraFERTH,
                MarafiberCode1 = parm.MarafiberCode1,
                MarafiberCode2 = parm.MarafiberCode2,
                MarafiberCode3 = parm.MarafiberCode3,
                MarafiberCode4 = parm.MarafiberCode4,
                MarafiberCode5 = parm.MarafiberCode5,
                MarafiberPart1 = parm.MarafiberPart1,
                MarafiberPart2 = parm.MarafiberPart2,
                MarafiberPart3 = parm.MarafiberPart3,
                MarafiberPart4 = parm.MarafiberPart4,
                MarafiberPart5 = parm.MarafiberPart5,
                MaraFORMT = parm.MaraFORMT,
                MarafreeChar = parm.MarafreeChar,
                MarafshMgAt1 = parm.MarafshMgAt1,
                MarafshMgAt2 = parm.MarafshMgAt2,
                MarafshMgAt3 = parm.MarafshMgAt3,
                MarafshScMid = parm.MarafshScMid,
                MarafshSeaim = parm.MarafshSeaim,
                MarafshSealv = parm.MarafshSealv,
                MaraFUELG = parm.MaraFUELG,
                MaragdsRelevant = parm.MaragdsRelevant,
                MaraGENNR = parm.MaraGENNR,
                MaraGEWEI = parm.MaraGEWEI,
                MaraGEWTO = parm.MaraGEWTO,
                MaraGROES = parm.MaraGROES,
                MaragtinVariant = parm.MaragtinVariant,
                MaraHAZMAT = parm.MaraHAZMAT,
                MaraHERKL = parm.MaraHERKL,
                MaraHNDLCODE = parm.MaraHNDLCODE,
                MaraHOEHE = parm.MaraHOEHE,
                MaraHUTYP = parm.MaraHUTYP,
                MarahutypDflt = parm.MarahutypDflt,
                MaraIHIVI = parm.MaraIHIVI,
                MaraILOOS = parm.MaraILOOS,
                MaraIMATN = parm.MaraIMATN,
                MaraINHAL = parm.MaraINHAL,
                MaraINHBR = parm.MaraINHBR,
                MaraINHME = parm.MaraINHME,
                MaraIPMIPPRODUCT = parm.MaraIPMIPPRODUCT,
                MaraIPRKZ = parm.MaraIPRKZ,
                MaraKOSCH = parm.MaraKOSCH,
                MaraKUNNR = parm.MaraKUNNR,
                MaraKZEFF = parm.MaraKZEFF,
                MaraKZGVH = parm.MaraKZGVH,
                MaraKZKFG = parm.MaraKZKFG,
                MaraKZKUP = parm.MaraKZKUP,
                MaraKZNFM = parm.MaraKZNFM,
                MaraKZREV = parm.MaraKZREV,
                MaraKZUMW = parm.MaraKZUMW,
                MaraKZWSM = parm.MaraKZWSM,
                MaraLABOR = parm.MaraLABOR,
                MaraLAEDA = parm.MaraLAEDA,
                MaraLAENG = parm.MaraLAENG,
                MaraLIQDT = parm.MaraLIQDT,
                MaraloglevReto = parm.MaraloglevReto,
                MaraLOGUNIT = parm.MaraLOGUNIT,
                MaraLVORM = parm.MaraLVORM,
                MaraMAGRV = parm.MaraMAGRV,
                MaraMANDT = parm.MaraMANDT,
                MaraMATFI = parm.MaraMATFI,
                MaraMATKL = parm.MaraMATKL,
                MaraMATNR = parm.MaraMATNR,
                MaraMAXB = parm.MaraMAXB,
                MaraMAXC = parm.MaraMAXC,
                MaramaxcTol = parm.MaramaxcTol,
                MaramaxdimUom = parm.MaramaxdimUom,
                MaraMAXH = parm.MaraMAXH,
                MaraMAXL = parm.MaraMAXL,
                MaraMBRSH = parm.MaraMBRSH,
                MaraMCOND = parm.MaraMCOND,
                MaraMEABM = parm.MaraMEABM,
                MaraMEDIUM = parm.MaraMEDIUM,
                MaraMEINS = parm.MaraMEINS,
                MaraMFRGR = parm.MaraMFRGR,
                MaraMFRNR = parm.MaraMFRNR,
                MaraMFRPN = parm.MaraMFRPN,
                MaraMHDHB = parm.MaraMHDHB,
                MaraMHDLP = parm.MaraMHDLP,
                MaraMHDRZ = parm.MaraMHDRZ,
                MaraMLGUT = parm.MaraMLGUT,
                MaraMPROF = parm.MaraMPROF,
                MaraMSTAE = parm.MaraMSTAE,
                MaraMSTAV = parm.MaraMSTAV,
                MaraMSTDE = parm.MaraMSTDE,
                MaraMSTDV = parm.MaraMSTDV,
                MaraMTART = parm.MaraMTART,
                MaramtposMara = parm.MaramtposMara,
                MaraNORMT = parm.MaraNORMT,
                MaraNRFHG = parm.MaraNRFHG,
                MaraNSNID = parm.MaraNSNID,
                MaraNTGEW = parm.MaraNTGEW,
                MaraNUMTP = parm.MaraNUMTP,
                MaraPACKCODE = parm.MaraPACKCODE,
                MaraPICNUM = parm.MaraPICNUM,
                MaraPILFERABLE = parm.MaraPILFERABLE,
                MaraPLGTP = parm.MaraPLGTP,
                MaraPMATA = parm.MaraPMATA,
                MaraPRDHA = parm.MaraPRDHA,
                MaraPROFL = parm.MaraPROFL,
                MaraPRZUS = parm.MaraPRZUS,
                MarapsSmartform = parm.MarapsSmartform,
                MaraPSTAT = parm.MaraPSTAT,
                MaraQGRP = parm.MaraQGRP,
                MaraQMPUR = parm.MaraQMPUR,
                MaraQQTIME = parm.MaraQQTIME,
                MaraQQTIMEUOM = parm.MaraQQTIMEUOM,
                MaraRAUBE = parm.MaraRAUBE,
                MaraRBNRM = parm.MaraRBNRM,
                MaraRDMHD = parm.MaraRDMHD,
                MaraRETDELC = parm.MaraRETDELC,
                MaraRMATP = parm.MaraRMATP,
                MaraSAISJ = parm.MaraSAISJ,
                MaraSAISO = parm.MaraSAISO,
                MaraSAITY = parm.MaraSAITY,
                MaraSATNR = parm.MaraSATNR,
                MaraSERIAL = parm.MaraSERIAL,
                MaraSERLV = parm.MaraSERLV,
                MarasgtCovsa = parm.MarasgtCovsa,
                MarasgtCsgr = parm.MarasgtCsgr,
                MarasgtRel = parm.MarasgtRel,
                MarasgtScope = parm.MarasgtScope,
                MarasgtStat = parm.MarasgtStat,
                MaraSIZE1 = parm.MaraSIZE1,
                Marasize1Atinn = parm.Marasize1Atinn,
                MaraSIZE2 = parm.MaraSIZE2,
                Marasize2Atinn = parm.Marasize2Atinn,
                MarasledBbd = parm.MarasledBbd,
                MaraSPART = parm.MaraSPART,
                MaraSPROF = parm.MaraSPROF,
                MaraSTFAK = parm.MaraSTFAK,
                MaraSTOFF = parm.MaraSTOFF,
                MaraTAKLV = parm.MaraTAKLV,
                MaratareVar = parm.MaratareVar,
                MaraTEMPB = parm.MaraTEMPB,
                MaratextileCompInd = parm.MaratextileCompInd,
                MaraTRAGR = parm.MaraTRAGR,
                MaraVABME = parm.MaraVABME,
                MaraVHART = parm.MaraVHART,
                MaraVOLEH = parm.MaraVOLEH,
                MaraVOLTO = parm.MaraVOLTO,
                MaraVOLUM = parm.MaraVOLUM,
                MaraVPREH = parm.MaraVPREH,
                MaraVPSTA = parm.MaraVPSTA,
                MaraWEORA = parm.MaraWEORA,
                MaraWESCH = parm.MaraWESCH,
                MaraWHMATGR = parm.MaraWHMATGR,
                MaraWHSTC = parm.MaraWHSTC,
                MaraWRKST = parm.MaraWRKST,
                MaraXCHPF = parm.MaraXCHPF,
                MaraXGCHP = parm.MaraXGCHP,
                MaraZEIAR = parm.MaraZEIAR,
                MaraZEIFO = parm.MaraZEIFO,
                MaraZEINR = parm.MaraZEINR,
                MaraZEIVR = parm.MaraZEIVR,
                UDF01 = parm.UDF01,
                UDF02 = parm.UDF02,
                UDF03 = parm.UDF03,
                UDF04 = parm.UDF04,
                UDF05 = parm.UDF05,
                UDF06 = parm.UDF06,
                UDF51 = parm.UDF51,
                UDF52 = parm.UDF52,
                UDF53 = parm.UDF53,
                UDF54 = parm.UDF54,
                UDF55 = parm.UDF55,
                UDF56 = parm.UDF56,
                Remark = parm.Remark,
            });
            return response;
        }

        /// <summary>
        /// 清空常规物料数据
        /// </summary>
        /// <returns></returns>
        public void TruncateMmMara()
        {
            Truncate();
        }
        #endregion
    }
}